export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCESS = 'ADD_PRODUCT_SUCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const COMENZAR_DESCARGA_PRODUCTOS_EXITO = 'COMENZAR_DESCARGA_PRODUCTOS_EXITO';
export const COMENZAR_DESCARGA_PRODUCTOS_ERROR = 'COMENZAR_DESCARGA_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';
